server:
  port: 8080


spring:
  datasource:
    url: ${CROCOBET_DB_URL}
    username: ${CROCOBET_USER}
    password: ${CROCOBET_PASSWORD}
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


jwt:
  secret-key: ${JAVA_COURSE_JWT_KEY}

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html



